### ISSUE TITLE
Make demo code available

### ISSUE THREAD

**Issue by adsteel** [JakeSidSmith/react-reorder#50]
Thanks for your work on this, it looks great. Could you make the demo code available?

**Comment by JakeSidSmith** [comment]
Yeah, this project does need a refactor (which would include adding example code). Until then you could check out the [gh-pages](https://github.com/JakeSidSmith/react-reorderable/tree/gh-pages) branch, but it's not written with JSX, so it may look a little confusing.

**Comment by adsteel** [comment]
This is great, thank you!

**Comment by JakeSidSmith** [comment]
Update: just released `3.0.0-alpha.0` on npm. I'd suggest checking out this version, it should be far more stable than the existing release, fixes a lot of bugs, and adds the ability to drag between lists. :)

See the readme after installation, there's been a considerable change to the interface.

Examples added to repo in version 3 alpha.

**Comment by JakeSidSmith** [comment]
Assuming fixed.
