### ISSUE TITLE
React should not be a dependency

### ISSUE THREAD

**Issue by SystemParadox** [JakeSidSmith/react-reorder#61]
This is working great with react 0.14.6 (apart from some warnings!), but only if I manually delete `node_modules/react-reorder/node_modules/react`. Otherwise, it throws horrible errors about "something is calling a react component directly", because react-reorder has it's own react 0.12 dependency (at least on the npm version. On github this is `react < 0.14`, which would still have the same problem).

Please could the react dependency either be removed, changed to a peerDependency (strongly recommended), and/or made much much more lenient (like `react >= 0.12` or `react *`). At the moment it's better to risk getting an incompatible react version than to end up with multiple copies of react in the tree.

Thanks.

**Comment by JakeSidSmith** [comment]
Sorry for the delay - busy times.

PR open here: https://github.com/JakeSidSmith/react-reorder/pull/62

Could you have a look over for me, @SystemParadox ?

Thanks.
