### ISSUE TITLE
Dodgy input focus when dragging on mobile devices

### ISSUE THREAD

**Issue by MarshallOfSound** [JakeSidSmith/react-reorder#65]
When you have an input field inside the draggable component it is really hard to focus on it on a mobile device.  I'm assuming this is because it is absorbing the touch/click events

**Comment by JakeSidSmith** [comment]
I have a few fixes to make related to #63 and so I'll try to get a fix for this issue in with the next release. :)

**Comment by MarshallOfSound** [comment]
I found a workaround which involves calling `stopPropagation` on any touch event on input fields inside the draggable components if that helps? :+1:

**Comment by JakeSidSmith** [comment]
Hey, @MarshallOfSound clearing up some old issues. Would you say this is a suitable solution, and therefore this issue is fixed? :)

**Comment by MarshallOfSound** [comment]
Yeah 👍
