### ISSUE TITLE
Rethink

### ISSUE THREAD

**Issue by JakeSidSmith** [JakeSidSmith/react-reorder#66]
Refactor:

* No mutation (as in #63)
* Remove `setState` where component updates are not required
* Support [immutablejs](https://facebook.github.io/immutable-js/)
* No new list in callback? Provide only previous and next indices?
* Allow defining `listComponent` and `itemComponent` (default to `ul` and `li`)
* Allow defining `listProps` and `itemProps` which will be applied to these components
* Allow `itemKey` to be a function (for getting keys from immutable objects)
* Clone item components for rendering, or use functional components?
* Multi-select components to reorder

```javascript
/* Work in progress */

const Item = (props) => (
  <div {...props}>
    
  </div>
);

class App extends Component {
  render() {
    return (
      <Reorder
        listComponent="div"
        itemComponent={Item}
        
      />
    );
  }
}
```

**Comment by oyeanuj** [comment]
Subscribed! Would love to try it out whenever it is ready to play with, even if in a branch!

**Comment by oyeanuj** [comment]
Hey @JakeSidSmith, Just wanted to get a sense of the progress and timing on this. This and #59 would be amazing additions to this library. I don't mean to be pushy but just wanted to get a rough idea so I can plan some of my work accordingly.

Thank you :)

**Comment by JakeSidSmith** [comment]
@oyeanuj Hey, I'm sorry it's been so long. I have had a lot of stuff going on recently, and other libraries to maintain.

You should be happy to hear that I have now started work on the rethink here: #71, and will be focussing on this until it's finished, unless anything else should come up. :)

**Comment by oyeanuj** [comment]
Awesome, thanks for the update! Looking forward to the new version and will follow #71 as well!

**Comment by JakeSidSmith** [comment]
@oyeanuj gonna close this issue, as it's a bit outdated. Follow #71 for updates. :)
