### ISSUE TITLE
  var root = this || window; causes compile error

### ISSUE THREAD

**Issue by rmoylan** [JakeSidSmith/react-reorder#67]
This is causing a window is not defined error on line 459. I am using it in a universal web app. I removed the reference to window, and all seems to be fine. Has anyone else ran into this issue?

**Comment by JakeSidSmith** [comment]
What are you compiling with?

**Comment by rmoylan** [comment]
importing using es6 with babel, and webpack for module bundling/compiling.

**Comment by JakeSidSmith** [comment]
OK, thanks for bringing this to my attention. Not had much experience with webpack myself, but I'll take a look.

Could you post your npm build script and or webpack configuration?

**Comment by rmoylan** [comment]
That would probably be a lot. But, I am using the rern starter at https://github.com/pthm/rern-starter . It is a port of the mern starter kit. You could pull that down and run tests off that. I forked the library, and i'll see if I can figure anything out too.

**Comment by JakeSidSmith** [comment]
Kk, I'll setup a project using that when I've got some free time. Seems like an odd error to be getting. No idea off the top of my head, what'd cause that problem.

**Comment by HriBB** [comment]
@JakeSidSmith please review #68 and let me know if it's OK ;)

**Comment by JakeSidSmith** [comment]
Have left you a comment. But would like to keep discussion here.

Are you using the same tools to build as rmoylan ?

**Comment by JakeSidSmith** [comment]
Fixed in #68 and released as `2.1.0`
