### ISSUE TITLE
Cannot sort via touch due to page scroll

### ISSUE THREAD

**Issue by tmm1** [JakeSidSmith/react-reorder#73]
The demos work well on mobile devices, but if you remove the fixed height on the container it becomes impossible to reorder. As you drag an item, the entire page scrolls in the opposite direction and the element stays in the same position.

One way to fix this is to set `window.ontouchmove = (e) => e.preventDefault()` while an item is being dragged.

**Comment by JakeSidSmith** [comment]
Update: just released `3.0.0-alpha.0` on npm. I'd suggest checking out this version, it should be far more stable than the existing release, fixes a lot of bugs, and adds the ability to drag between lists. :)

See the readme after installation, there's been a considerable change to the interface.

**Comment by JakeSidSmith** [comment]
Closing due to lack of response.
