### ISSUE TITLE
Warning: This synthetic event is reused for performance reasons.

### ISSUE THREAD

**Issue by HriBB** [JakeSidSmith/react-reorder#75]
Hey

I'm seeing this warning on "mobile", via chrome developer tools.

```
Warning: This synthetic event is reused for performance reasons.
If you're seeing this, you're adding a new property in the synthetic event object.
The property is never released.
```

See https://fb.me/react-event-pooling for more information.

In `handleTouchEvents` you're adding `clientX` and `clientY` to the event object, which I guess is bad in React.

```
itemDown: function (item, index, event) {
  this.handleTouchEvents(event);
  ...
}

handleTouchEvents: function (event) {
  if (event.touches && event.touches.length) {
    event.clientX = event.touches[0].clientX;
    event.clientY = event.touches[0].clientY;
  }
},
```

Maybe you can include that in the rewrite? Otherwise I can take a look and make a PR.

**Comment by HriBB** [comment]
Ohh and I just realized that I cannot tap on `IconButton` in the list.

**Comment by JakeSidSmith** [comment]
Hey, @HriBB going through a big re-write at the moment in which this is already fixed. :)

#71

**Comment by HriBB** [comment]
@JakeSidSmith I thought so, just wanted to make sure this is fixed. Closing.
