### ISSUE TITLE
placeholder class is not added when dragging input fields

### ISSUE THREAD

**Issue by garth** [JakeSidSmith/react-reorder#76]
Drag a non-input field and a .placeholder is added to the target. Drag an input field and .placeholder is not added.

![drag-input](https://cloud.githubusercontent.com/assets/4643/21106542/c7679298-c08e-11e6-96c6-5da313168046.gif)

**Comment by JakeSidSmith** [comment]
That's an odd one. Potentially due to an `event.preventDefault` on one of the inputs handlers? Not to worry, new major version in the making (#71) that should solve all existing issues. I'll make sure this is included.

**Comment by JakeSidSmith** [comment]
Update: just released `3.0.0-alpha.0` on npm. I'd suggest checking out this version, it should be far more stable than the existing release, fixes a lot of bugs, and adds the ability to drag between lists. :)

See the readme after installation, there's been a considerable change to the interface.

**Comment by JakeSidSmith** [comment]
Any update on this? If not, I'll close this issue.
