### ISSUE TITLE
Warning with react 15.5.0

### ISSUE THREAD

**Issue by romamatusevich** [JakeSidSmith/react-reorder#79]
Warning: Reorder: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by JakeSidSmith** [comment]
Oh, jeez. :|

Will add this to v3 alpha.

**Comment by romamatusevich** [comment]
I created an example of using babelify to support the usage of React.Component instead of React.createClass:
https://github.com/romamatusevich/react-reorder/commit/dacd021cc60f05e1a29ad6ce0448ffd491a33b2c

What do you think about creation of the support release 2.1.1 to prevent warnings with react 15.5.0? I understand that version 3 alpha is in development, but I am not sure that it is fully stable.

**Comment by JakeSidSmith** [comment]
@romamatusevich it should me more stable than the existing versions, but I don't think enough people have tested it yet. I'll release a patch of version 2 with the `react-create-class` lib, as I think the move to ES6 may cause issues with binding.

**Comment by romamatusevich** [comment]
Sounds good. During testing I faced with binding issues and just added bindings to constructor:

```
constructor(props) {
    super(props);

    this.state = { list: this.props.list || [] };
    this.dragScrollY = this.dragScrollY.bind(this);
    this.onMouseUp = this.onMouseUp.bind(this);
    this.onMouseMove = this.onMouseMove.bind(this);
}
```

https://github.com/romamatusevich/react-reorder/commit/dacd021cc60f05e1a29ad6ce0448ffd491a33b2c#diff-1fdf421c05c1140f6d71444ea2b27638R418

**Comment by JakeSidSmith** [comment]
Gonna release in a sec after a little testing. There's another couple of fixes that should go into v2. But I'll sort those out after this. :)

- [ ] `event.preventDefault` when dragging on mobile to prevent scrolling
- [ ] `event.persist` for React 15+

**Comment by JakeSidSmith** [comment]
@romamatusevich care to review? https://github.com/JakeSidSmith/react-reorder/pull/80

**Comment by romamatusevich** [comment]
@JakeSidSmith, sure, will review

**Comment by wmertens** [comment]
With React v16 imminent, how about releasing v3?

**Comment by JakeSidSmith** [comment]
@wmertens there are a couple of known bugs that need to be sorted first. Will try to sort these as soon as I can.

**Comment by wmertens** [comment]
@JakeSidSmith Can you mark those in a milestone? I might be able to help a little bit

**Comment by JakeSidSmith** [comment]
@wmertens keeping track of them here: https://github.com/JakeSidSmith/react-reorder/issues/78

**Comment by JakeSidSmith** [comment]
Gonna take a look at the unmounting bug today.
